development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:16eb3a08b54ba3281a0678c7ccddd42e@crestfish.redistogo.com:10262/" } %>
  channel_prefix: scordid_production
